CREATE TABLE IF NOT EXISTS HOTEL (
   ID BIGINT PRIMARY KEY NOT NULL,
   NAME VARCHAR NOT NULL,
   ID_ADDRESS INT  NOT NULL,

   CONSTRAINT fk_address
   FOREIGN KEY(ID_ADDRESS)
   REFERENCES ADDRESS(ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_HOTEL
INCREMENT 1
START 1
OWNED BY HOTEL.ID;

CREATE INDEX ON HOTEL (ID_ADDRESS);