CREATE TABLE IF NOT EXISTS ACCOMMODATION (
   ID BIGINT PRIMARY KEY NOT NULL,
   ROOM_QUANTITY INT  NOT NULL,
   MAX_CAPACITY INT  NOT NULL,
   DAILY_RATE DECIMAL NOT NULL,
   IS_AVAILABLE BOOLEAN NOT NULL,
   ID_HOTEL INT NOT NULL,
   CONSTRAINT FK_HOTEL
   FOREIGN KEY(ID_HOTEL)
   REFERENCES HOTEL(ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_ACCOMMODATION
INCREMENT 1
START 1
OWNED BY ACCOMMODATION.ID;

CREATE INDEX ON ACCOMMODATION (ID_HOTEL);
CREATE INDEX ON ACCOMMODATION (ROOM_QUANTITY);
CREATE INDEX ON ACCOMMODATION (MAX_CAPACITY);
CREATE INDEX ON ACCOMMODATION (ID_HOTEL);