CREATE TABLE IF NOT EXISTS BOOKING (
   ID BIGINT PRIMARY KEY NOT NULL,
   TOTAL_VALUE DECIMAL NOT NULL,
   BOOKING_DATE TIMESTAMPTZ NOT NULL,
   CHECK_IN_DATE TIMESTAMPTZ NOT NULL,
   CHECK_OUT_DATE TIMESTAMPTZ NOT NULL,
   CHECK_IN BOOLEAN NOT NULL,
   CHECK_OUT BOOLEAN NOT NULL,
   STATUS VARCHAR NOT NULL,
   ID_CLIENT INT NOT NULL,
   ID_ACCOMMODATION INT NOT NULL,

   CONSTRAINT FK_CLIENT
   FOREIGN KEY(ID_CLIENT)
   REFERENCES CLIENT(ID),

   CONSTRAINT FK_ACCOMMODATION
   FOREIGN KEY(ID_ACCOMMODATION)
   REFERENCES ACCOMMODATION(ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_BOOKING
INCREMENT 1
START 1
OWNED BY BOOKING.ID;

CREATE INDEX ON BOOKING (ID_CLIENT);
CREATE INDEX ON BOOKING (ID_ACCOMMODATION);
CREATE INDEX ON BOOKING (CHECK_IN_DATE);
CREATE INDEX ON BOOKING (CHECK_OUT_DATE);